development:
  forest_env_secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImRhdGEiOnsidHlwZSI6InVzZXJzIiwiaWQiOiIzMTA3OCIsImF0dHJpYnV0ZXMiOnsiZmlyc3RfbmFtZSI6Ikh1Z28iLCJsYXN0X25hbWUiOiJNb3JpIiwiZW1haWwiOiJodWdvLm1vcmlAYmFsb3ViZXQuY29tIn19fSwiaWF0IjoxNTgyMDIwNDkwLCJleHAiOjE1ODIxOTMyOTAsImF1ZCI6IkZPUkVTVF9VU0VSUyIsImlzcyI6IkZPUkVTVF9BVVRIRU5USUNBVElPTl9TWVNURU0ifQ.L8up09GzYWBuTpIkL0W5nzsiFR6Eg_140ozeFkPi8BY
  forest_auth_secret: KJvJocM_84M1GqxBsNqGrg
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
